spring:
  thymeleaf:
    encoding: utf-8
    cache: false
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  datasource:
    url: jdbc:mysql://localhost:3306/lre_cea?characterEncoding=utf-8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver